spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    
    h2:
        console:
            enable: true
    
    sonar:
        url: ${SONAR_URL}
        token: ${SONAR_TOKEN}
        organization: ${SONAR_ORG}
        projectkey: ${SONAR_PROJECTKEY}
