spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    
    h2:
        console:
            enable: true
