name: Project CI Java

on:
  push:
    branches: ["master", "develop","feature/arch_structure"]

env:
  SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY}}
  SONAR_ORG: ${{secrets.SONAR_ORG}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up .env file
        run: |
          echo "DB_USERNAME=${{ env.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env

      - name: Run coverage scan
        run: mvn clean test jacoco:report sonar:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECTKEY}} -Dsonar.organization=${{env.SONAR_ORG}} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{env.SONAR_TOKEN}}
            